load("@bazel_skylib//lib:subpackages.bzl", "subpackages")
load("@rules_go//go:def.bzl", "go_library")

go_library(
    name = "uname",
    srcs = ["uname.go"],
    importpath = "github.com/DataDog/rshell/builtins/uname",
    visibility = ["//visibility:public"],
    deps = ["//builtins"],
)

filegroup(
    name = "srcs",
    srcs = glob(["**"]) + [
        "%s:srcs" % d
        for d in subpackages.all(
            allow_empty = True,
            fully_qualified = True,
        )
    ],
    visibility = ["//visibility:public"],
)
