load("@rules_go//go:def.bzl", "go_library", "go_test")

go_library(
    name = "cat",
    srcs = ["cat.go"],
    importpath = "github.com/DataDog/rshell/builtins/cat",
    visibility = ["//visibility:public"],
    deps = ["//builtins"],
)

go_test(
    name = "cat_test",
    srcs = [
        "builtin_cat_pentest_test.go",
        "cat_bench_test.go",
        "cat_gnu_compat_test.go",
        "cat_test.go",
    ],
    deps = [
        ":cat",
        "//builtins/testutil",
        "//interp",
        "@com_github_stretchr_testify//assert",
        "@com_github_stretchr_testify//require",
    ],
)
