load("@rules_go//go:def.bzl", "go_library", "go_test")

go_library(
    name = "grep",
    srcs = ["grep.go"],
    importpath = "github.com/DataDog/rshell/builtins/grep",
    visibility = ["//visibility:public"],
    deps = ["//builtins"],
)

go_test(
    name = "grep_test",
    srcs = [
        "builtin_grep_pentest_test.go",
        "grep_bench_test.go",
        "grep_test.go",
        "grep_vuln_hunt_test.go",
    ],
    deps = [
        ":grep",
        "//builtins/testutil",
        "//interp",
        "@com_github_stretchr_testify//assert",
        "@com_github_stretchr_testify//require",
    ],
)
