load("@gazelle//:def.bzl", "gazelle")
load("@package_metadata//licenses/rules:license.bzl", "license")
load("@package_metadata//rules:package_metadata.bzl", "package_metadata")

package(
    default_package_metadata = [":package_metadata"],
    default_visibility = ["//visibility:public"],
)

# gazelle:prefix github.com/DataDog/rshell
gazelle(name = "gazelle")

package_metadata(
    name = "package_metadata",
    attributes = [":license"],
    purl = "pkg:golang/github.com/DataDog/rshell",
)

license(
    name = "license",
    kind = "@package_metadata//licenses/spdx:Apache-2.0",
    text = "LICENSE",
)
