load("@rules_go//go:def.bzl", "go_library", "go_test")

go_library(
    name = "wc",
    srcs = [
        "wc.go",
        "wc_isdir_unix.go",
        "wc_isdir_windows.go",
    ],
    importpath = "github.com/DataDog/rshell/builtins/wc",
    visibility = ["//visibility:public"],
    deps = ["//builtins"],
)

go_test(
    name = "wc_test",
    srcs = [
        "builtin_wc_pentest_test.go",
        "wc_bench_test.go",
        "wc_gnu_compat_test.go",
        "wc_test.go",
        "wc_unix_test.go",
        "wc_vuln_hunt_test.go",
    ],
    deps = [
        "//builtins/testutil",
        "//interp",
        "@com_github_stretchr_testify//assert",
        "@com_github_stretchr_testify//require",
    ],
)
