load("@rules_go//go:def.bzl", "go_library", "go_test")

go_library(
    name = "systemctl",
    srcs = ["systemctl.go"],
    importpath = "github.com/DataDog/rshell/builtins/systemctl",
    visibility = ["//visibility:public"],
    deps = ["//builtins"],
)

go_test(
    name = "systemctl_test",
    srcs = ["systemctl_test.go"],
    embed = [":systemctl"],
    deps = [
        "//builtins",
        "@com_github_spf13_pflag//:pflag",
        "@com_github_stretchr_testify//assert",
        "@com_github_stretchr_testify//require",
    ],
)
