load("@bazel_skylib//lib:subpackages.bzl", "subpackages")
load("@rules_go//go:def.bzl", "go_library", "go_test")

go_library(
    name = "procnetroute",
    srcs = [
        "procnetroute.go",
        "procnetroute_linux.go",
        "procnetroute_other.go",
    ],
    importpath = "github.com/DataDog/rshell/builtins/internal/procnetroute",
    visibility = ["//builtins:__subpackages__"],
    deps = ["//builtins/internal/procpath"],
)

go_test(
    name = "procnetroute_test",
    size = "small",
    srcs = [
        "procnetroute_linux_vuln_hunt_test.go",
        "procnetroute_other_vuln_hunt_test.go",
        "procnetroute_vuln_hunt_test.go",
    ],
    embed = [":procnetroute"],
)

filegroup(
    name = "srcs",
    srcs = glob(["**"]) + [
        "%s:srcs" % d
        for d in subpackages.all(
            allow_empty = True,
            fully_qualified = True,
        )
    ],
    visibility = ["//visibility:public"],
)
