load("@bazel_skylib//lib:subpackages.bzl", "subpackages")
load("@rules_go//go:def.bzl", "go_library", "go_test")

go_library(
    name = "false",
    srcs = ["false.go"],
    importpath = "github.com/DataDog/rshell/builtins/false",
    visibility = ["//visibility:public"],
    deps = ["//builtins"],
)

go_test(
    name = "false_test",
    size = "small",
    srcs = ["false_vuln_hunt_test.go"],
    embed = [":false"],
    deps = ["//builtins"],
)

filegroup(
    name = "srcs",
    srcs = glob(["**"]) + [
        "%s:srcs" % d
        for d in subpackages.all(
            allow_empty = True,
            fully_qualified = True,
        )
    ],
    visibility = ["//visibility:public"],
)
