load("@bazel_skylib//lib:subpackages.bzl", "subpackages")
load("@rules_go//go:def.bzl", "go_library")

go_library(
    name = "winpoll",
    srcs = [
        "winpoll_other.go",
        "winpoll_windows.go",
    ],
    importpath = "github.com/DataDog/rshell/builtins/internal/winpoll",
    visibility = ["//builtins:__subpackages__"],
    deps = select({
        "@rules_go//go/platform:windows": [
            "@org_golang_x_sys//windows",
        ],
        "//conditions:default": [],
    }),
)

filegroup(
    name = "srcs",
    srcs = glob(["**"]) + [
        "%s:srcs" % d
        for d in subpackages.all(
            allow_empty = True,
            fully_qualified = True,
        )
    ],
    visibility = ["//visibility:public"],
)
