// Unless explicitly stated otherwise all files in this repository are licensed
// under the Apache License Version 2.0.
// This product includes software developed at Datadog (https://www.datadoghq.com/).
// Copyright 2026-present Datadog, Inc.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.0
// source: privilegedhelper/private_action.proto

package privilegedhelper

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	structpb "google.golang.org/protobuf/types/known/structpb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// PrivateActionTask is the security-relevant subset of the PAR task wire
// format. Field numbers intentionally match private_actions.proto in the
// datadog-agent repository. Unknown fields remain covered by the backend
// signature and are ignored when decoding.
type PrivateActionTask struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	ActionName     string                 `protobuf:"bytes,1,opt,name=action_name,json=actionName,proto3" json:"action_name,omitempty"`
	BundleId       string                 `protobuf:"bytes,2,opt,name=bundle_id,json=bundleId,proto3" json:"bundle_id,omitempty"`
	OrgId          int64                  `protobuf:"varint,3,opt,name=org_id,json=orgId,proto3" json:"org_id,omitempty"`
	TaskId         string                 `protobuf:"bytes,4,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	Inputs         *structpb.Struct       `protobuf:"bytes,6,opt,name=inputs,proto3" json:"inputs,omitempty"`
	ConnectionInfo *ConnectionInfo        `protobuf:"bytes,10,opt,name=connection_info,json=connectionInfo,proto3" json:"connection_info,omitempty"`
	ExpirationTime *timestamppb.Timestamp `protobuf:"bytes,11,opt,name=expiration_time,json=expirationTime,proto3" json:"expiration_time,omitempty"`
	SystemInputs   *SystemInputs          `protobuf:"bytes,13,opt,name=system_inputs,json=systemInputs,proto3" json:"system_inputs,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *PrivateActionTask) Reset() {
	*x = PrivateActionTask{}
	mi := &file_privilegedhelper_private_action_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PrivateActionTask) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PrivateActionTask) ProtoMessage() {}

func (x *PrivateActionTask) ProtoReflect() protoreflect.Message {
	mi := &file_privilegedhelper_private_action_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PrivateActionTask.ProtoReflect.Descriptor instead.
func (*PrivateActionTask) Descriptor() ([]byte, []int) {
	return file_privilegedhelper_private_action_proto_rawDescGZIP(), []int{0}
}

func (x *PrivateActionTask) GetActionName() string {
	if x != nil {
		return x.ActionName
	}
	return ""
}

func (x *PrivateActionTask) GetBundleId() string {
	if x != nil {
		return x.BundleId
	}
	return ""
}

func (x *PrivateActionTask) GetOrgId() int64 {
	if x != nil {
		return x.OrgId
	}
	return 0
}

func (x *PrivateActionTask) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

func (x *PrivateActionTask) GetInputs() *structpb.Struct {
	if x != nil {
		return x.Inputs
	}
	return nil
}

func (x *PrivateActionTask) GetConnectionInfo() *ConnectionInfo {
	if x != nil {
		return x.ConnectionInfo
	}
	return nil
}

func (x *PrivateActionTask) GetExpirationTime() *timestamppb.Timestamp {
	if x != nil {
		return x.ExpirationTime
	}
	return nil
}

func (x *PrivateActionTask) GetSystemInputs() *SystemInputs {
	if x != nil {
		return x.SystemInputs
	}
	return nil
}

type SystemInputs struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Input:
	//
	//	*SystemInputs_RemoteAction
	Input         isSystemInputs_Input `protobuf_oneof:"input"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SystemInputs) Reset() {
	*x = SystemInputs{}
	mi := &file_privilegedhelper_private_action_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SystemInputs) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SystemInputs) ProtoMessage() {}

func (x *SystemInputs) ProtoReflect() protoreflect.Message {
	mi := &file_privilegedhelper_private_action_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SystemInputs.ProtoReflect.Descriptor instead.
func (*SystemInputs) Descriptor() ([]byte, []int) {
	return file_privilegedhelper_private_action_proto_rawDescGZIP(), []int{1}
}

func (x *SystemInputs) GetInput() isSystemInputs_Input {
	if x != nil {
		return x.Input
	}
	return nil
}

func (x *SystemInputs) GetRemoteAction() *RemoteAction {
	if x != nil {
		if x, ok := x.Input.(*SystemInputs_RemoteAction); ok {
			return x.RemoteAction
		}
	}
	return nil
}

type isSystemInputs_Input interface {
	isSystemInputs_Input()
}

type SystemInputs_RemoteAction struct {
	RemoteAction *RemoteAction `protobuf:"bytes,1,opt,name=remote_action,json=remoteAction,proto3,oneof"`
}

func (*SystemInputs_RemoteAction) isSystemInputs_Input() {}

type RemoteAction struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	AllowedCommands []string               `protobuf:"bytes,1,rep,name=allowed_commands,json=allowedCommands,proto3" json:"allowed_commands,omitempty"`
	AllowedPaths    []string               `protobuf:"bytes,2,rep,name=allowed_paths,json=allowedPaths,proto3" json:"allowed_paths,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *RemoteAction) Reset() {
	*x = RemoteAction{}
	mi := &file_privilegedhelper_private_action_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemoteAction) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoteAction) ProtoMessage() {}

func (x *RemoteAction) ProtoReflect() protoreflect.Message {
	mi := &file_privilegedhelper_private_action_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoteAction.ProtoReflect.Descriptor instead.
func (*RemoteAction) Descriptor() ([]byte, []int) {
	return file_privilegedhelper_private_action_proto_rawDescGZIP(), []int{2}
}

func (x *RemoteAction) GetAllowedCommands() []string {
	if x != nil {
		return x.AllowedCommands
	}
	return nil
}

func (x *RemoteAction) GetAllowedPaths() []string {
	if x != nil {
		return x.AllowedPaths
	}
	return nil
}

type ConnectionInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RunnerId      string                 `protobuf:"bytes,4,opt,name=runner_id,json=runnerId,proto3" json:"runner_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConnectionInfo) Reset() {
	*x = ConnectionInfo{}
	mi := &file_privilegedhelper_private_action_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConnectionInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConnectionInfo) ProtoMessage() {}

func (x *ConnectionInfo) ProtoReflect() protoreflect.Message {
	mi := &file_privilegedhelper_private_action_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConnectionInfo.ProtoReflect.Descriptor instead.
func (*ConnectionInfo) Descriptor() ([]byte, []int) {
	return file_privilegedhelper_private_action_proto_rawDescGZIP(), []int{3}
}

func (x *ConnectionInfo) GetRunnerId() string {
	if x != nil {
		return x.RunnerId
	}
	return ""
}

var File_privilegedhelper_private_action_proto protoreflect.FileDescriptor

const file_privilegedhelper_private_action_proto_rawDesc = "" +
	"\n" +
	"%privilegedhelper/private_action.proto\x12\x1fdatadog.rshell.privilegedhelper\x1a\x1cgoogle/protobuf/struct.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"\xb7\x03\n" +
	"\x11PrivateActionTask\x12\x1f\n" +
	"\vaction_name\x18\x01 \x01(\tR\n" +
	"actionName\x12\x1b\n" +
	"\tbundle_id\x18\x02 \x01(\tR\bbundleId\x12\x15\n" +
	"\x06org_id\x18\x03 \x01(\x03R\x05orgId\x12\x17\n" +
	"\atask_id\x18\x04 \x01(\tR\x06taskId\x12/\n" +
	"\x06inputs\x18\x06 \x01(\v2\x17.google.protobuf.StructR\x06inputs\x12X\n" +
	"\x0fconnection_info\x18\n" +
	" \x01(\v2/.datadog.rshell.privilegedhelper.ConnectionInfoR\x0econnectionInfo\x12C\n" +
	"\x0fexpiration_time\x18\v \x01(\v2\x1a.google.protobuf.TimestampR\x0eexpirationTime\x12R\n" +
	"\rsystem_inputs\x18\r \x01(\v2-.datadog.rshell.privilegedhelper.SystemInputsR\fsystemInputsJ\x04\b\a\x10\bJ\x04\b\b\x10\tJ\x04\b\t\x10\n" +
	"\"m\n" +
	"\fSystemInputs\x12T\n" +
	"\rremote_action\x18\x01 \x01(\v2-.datadog.rshell.privilegedhelper.RemoteActionH\x00R\fremoteActionB\a\n" +
	"\x05input\"^\n" +
	"\fRemoteAction\x12)\n" +
	"\x10allowed_commands\x18\x01 \x03(\tR\x0fallowedCommands\x12#\n" +
	"\rallowed_paths\x18\x02 \x03(\tR\fallowedPaths\"-\n" +
	"\x0eConnectionInfo\x12\x1b\n" +
	"\trunner_id\x18\x04 \x01(\tR\brunnerIdB,Z*github.com/DataDog/rshell/privilegedhelperb\x06proto3"

var (
	file_privilegedhelper_private_action_proto_rawDescOnce sync.Once
	file_privilegedhelper_private_action_proto_rawDescData []byte
)

func file_privilegedhelper_private_action_proto_rawDescGZIP() []byte {
	file_privilegedhelper_private_action_proto_rawDescOnce.Do(func() {
		file_privilegedhelper_private_action_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_privilegedhelper_private_action_proto_rawDesc), len(file_privilegedhelper_private_action_proto_rawDesc)))
	})
	return file_privilegedhelper_private_action_proto_rawDescData
}

var file_privilegedhelper_private_action_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_privilegedhelper_private_action_proto_goTypes = []any{
	(*PrivateActionTask)(nil),     // 0: datadog.rshell.privilegedhelper.PrivateActionTask
	(*SystemInputs)(nil),          // 1: datadog.rshell.privilegedhelper.SystemInputs
	(*RemoteAction)(nil),          // 2: datadog.rshell.privilegedhelper.RemoteAction
	(*ConnectionInfo)(nil),        // 3: datadog.rshell.privilegedhelper.ConnectionInfo
	(*structpb.Struct)(nil),       // 4: google.protobuf.Struct
	(*timestamppb.Timestamp)(nil), // 5: google.protobuf.Timestamp
}
var file_privilegedhelper_private_action_proto_depIdxs = []int32{
	4, // 0: datadog.rshell.privilegedhelper.PrivateActionTask.inputs:type_name -> google.protobuf.Struct
	3, // 1: datadog.rshell.privilegedhelper.PrivateActionTask.connection_info:type_name -> datadog.rshell.privilegedhelper.ConnectionInfo
	5, // 2: datadog.rshell.privilegedhelper.PrivateActionTask.expiration_time:type_name -> google.protobuf.Timestamp
	1, // 3: datadog.rshell.privilegedhelper.PrivateActionTask.system_inputs:type_name -> datadog.rshell.privilegedhelper.SystemInputs
	2, // 4: datadog.rshell.privilegedhelper.SystemInputs.remote_action:type_name -> datadog.rshell.privilegedhelper.RemoteAction
	5, // [5:5] is the sub-list for method output_type
	5, // [5:5] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_privilegedhelper_private_action_proto_init() }
func file_privilegedhelper_private_action_proto_init() {
	if File_privilegedhelper_private_action_proto != nil {
		return
	}
	file_privilegedhelper_private_action_proto_msgTypes[1].OneofWrappers = []any{
		(*SystemInputs_RemoteAction)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_privilegedhelper_private_action_proto_rawDesc), len(file_privilegedhelper_private_action_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_privilegedhelper_private_action_proto_goTypes,
		DependencyIndexes: file_privilegedhelper_private_action_proto_depIdxs,
		MessageInfos:      file_privilegedhelper_private_action_proto_msgTypes,
	}.Build()
	File_privilegedhelper_private_action_proto = out.File
	file_privilegedhelper_private_action_proto_goTypes = nil
	file_privilegedhelper_private_action_proto_depIdxs = nil
}
