load("@rules_go//go:def.bzl", "go_library", "go_test")

go_library(
    name = "pwd",
    srcs = ["pwd.go"],
    importpath = "github.com/DataDog/rshell/builtins/pwd",
    visibility = ["//visibility:public"],
    deps = ["//builtins"],
)

go_test(
    name = "pwd_test",
    srcs = [
        "builtin_pwd_pentest_test.go",
        "pwd_fuzz_test.go",
        "pwd_internal_test.go",
        "pwd_test.go",
        "pwd_unix_test.go",
        "pwd_vuln_hunt_test.go",
    ],
    data = glob(["testdata/**"]),
    embed = [":pwd"],
    deps = [
        "//builtins",
        "//builtins/testutil",
        "//interp",
        "@com_github_spf13_pflag//:pflag",
        "@com_github_stretchr_testify//assert",
        "@com_github_stretchr_testify//require",
    ],
)
