[package]
name = "rshell-analysis"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
publish.workspace = true

[[bin]]
name = "rshell-analysis"
path = "src/main.rs"

[dependencies]
thiserror.workspace = true
walkdir.workspace = true
syn = { version = "2", features = ["full", "visit"] }
proc-macro2 = { version = "1", default-features = false, features = ["span-locations"] }

[lints]
workspace = true
