load("@bazel_skylib//lib:subpackages.bzl", "subpackages")
load("@rules_go//go:def.bzl", "go_test")

go_test(
    name = "vmstat_test",
    size = "small",
    srcs = [
        "helpers_test.go",
        "vmstat_linux_test.go",
    ],
    deps = [
        "//internal/interpoption",
        "//interp",
        "@cc_mvdan_sh_v3//syntax",
    ] + select({
        "@rules_go//go/platform:android": [
            "//builtins/vmstat",
            "@com_github_stretchr_testify//assert",
            "@com_github_stretchr_testify//require",
        ],
        "@rules_go//go/platform:linux": [
            "//builtins/vmstat",
            "@com_github_stretchr_testify//assert",
            "@com_github_stretchr_testify//require",
        ],
        "//conditions:default": [],
    }),
)

filegroup(
    name = "srcs",
    srcs = glob(["**"]) + [
        "%s:srcs" % d
        for d in subpackages.all(
            allow_empty = True,
            fully_qualified = True,
        )
    ],
    visibility = ["//visibility:public"],
)
