load("@bazel_skylib//lib:subpackages.bzl", "subpackages")
load("@rules_go//go:def.bzl", "go_library", "go_test")

go_library(
    name = "echo",
    srcs = ["echo.go"],
    importpath = "github.com/DataDog/rshell/builtins/echo",
    visibility = ["//visibility:public"],
    deps = ["//builtins"],
)

go_test(
    name = "echo_test",
    size = "small",
    srcs = [
        "builtin_echo_pentest_test.go",
        "echo_test.go",
    ],
    deps = [
        "//builtins/testutil",
        "@com_github_stretchr_testify//assert",
    ],
)

filegroup(
    name = "srcs",
    srcs = glob(["**"]) + [
        "%s:srcs" % d
        for d in subpackages.all(
            allow_empty = True,
            fully_qualified = True,
        )
    ],
    visibility = ["//visibility:public"],
)
