load("@bazel_skylib//lib:subpackages.bzl", "subpackages")
load("@rules_go//go:def.bzl", "go_library", "go_test")

go_library(
    name = "uniq",
    srcs = ["uniq.go"],
    importpath = "github.com/DataDog/rshell/builtins/uniq",
    visibility = ["//visibility:public"],
    deps = ["//builtins"],
)

go_test(
    name = "uniq_test",
    size = "small",
    srcs = [
        "uniq_bench_test.go",
        "uniq_gnu_compat_test.go",
        "uniq_pentest_test.go",
        "uniq_test.go",
    ],
    deps = [
        "//builtins/testutil",
        "//interp",
        "@com_github_stretchr_testify//assert",
        "@com_github_stretchr_testify//require",
    ],
)

filegroup(
    name = "srcs",
    srcs = glob(["**"]) + [
        "%s:srcs" % d
        for d in subpackages.all(
            allow_empty = True,
            fully_qualified = True,
        )
    ],
    visibility = ["//visibility:public"],
)
