load("@rules_go//go:def.bzl", "go_test")

go_test(
    name = "ip_test",
    srcs = [
        "helpers_test.go",
        "ip_fuzz_test.go",
        "ip_linux_test.go",
        "ip_pentest_linux_test.go",
        "ip_route_fuzz_linux_test.go",
        "ip_test.go",
        "ip_vuln_hunt_linux_test.go",
    ],
    data = glob(["testdata/**"]),
    deps = [
        "//internal/interpoption",
        "//interp",
        "@cc_mvdan_sh_v3//syntax",
        "@com_github_stretchr_testify//assert",
        "@com_github_stretchr_testify//require",
    ] + select({
        "@rules_go//go/platform:android": [
            "//builtins/ip",
        ],
        "@rules_go//go/platform:linux": [
            "//builtins/ip",
        ],
        "//conditions:default": [],
    }),
)
