#!/usr/bin/env bash

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
source "$SCRIPT_DIR/lib.sh"

map_file="$REPO_ROOT/tests/awk_scenarios/upstream-map.yaml"
if [ ! -f "$map_file" ]; then
	die "rewrite map not found at $map_file"
fi

"$SCRIPT_DIR/fetch-gawk.sh" >/dev/null
"$SCRIPT_DIR/fetch-onetrueawk.sh" >/dev/null

inventory_file="$(mktemp)"
known_file="$(mktemp)"
missing_file="$(mktemp)"
trap 'rm -f "$inventory_file" "$known_file" "$missing_file"' EXIT

"$SCRIPT_DIR/list-rewrite-inventory.sh" >"$inventory_file"
awk '
	/^[[:space:]]*-[[:space:]]*suite:/ {
		suite = $3
		gsub(/^"|"$/, "", suite)
	}
	/^[[:space:]]*id:/ {
		id = $2
		gsub(/^"|"$/, "", id)
		if (suite != "" && id != "")
			print suite "\t" id
	}
' "$map_file" | LC_ALL=C sort -u >"$known_file"

awk -F '\t' '
	NR == FNR {
		known[$1 "\t" $2] = 1
		next
	}
	! known[$1 "\t" $2]
' "$known_file" "$inventory_file" >"$missing_file"

missing_count="$(wc -l <"$missing_file" | tr -d ' ')"
if [ "$missing_count" -eq 0 ]; then
	log "rewrite map already covers every fetched upstream test"
	exit 0
fi

{
	printf '\n# Upstream tests not rewritten yet. Generated by tools/awk-harness/run.sh sync-rewrite-map.\n'
	while IFS=$'\t' read -r suite id ref; do
		printf '\n  - suite: %s\n' "$suite"
		printf '    id: %s\n' "$id"
		printf '    ref: %s\n' "$ref"
		printf '    status: todo\n'
		printf '    reason: Original rshell rewrite not written yet.\n'
	done <"$missing_file"
} >>"$map_file"

log "added $missing_count todo entries to $map_file"
