load("@rules_go//go:def.bzl", "go_test")

go_test(
    name = "awk_test",
    srcs = ["awk_test.go"],
    deps = [
        "//internal/interpoption",
        "//interp",
        "@cc_mvdan_sh_v3//syntax",
        "@com_github_stretchr_testify//assert",
        "@com_github_stretchr_testify//require",
    ],
)
