load("@rules_go//go:def.bzl", "go_library", "go_test")

go_library(
    name = "head",
    srcs = ["head.go"],
    importpath = "github.com/DataDog/rshell/builtins/head",
    visibility = ["//visibility:public"],
    deps = ["//builtins"],
)

go_test(
    name = "head_test",
    srcs = [
        "builtin_head_pentest_test.go",
        "head_bench_test.go",
        "head_gnu_compat_test.go",
        "head_test.go",
        "head_unix_test.go",
        "head_windows_test.go",
    ],
    deps = [
        "//builtins/testutil",
        "//interp",
        "@com_github_stretchr_testify//assert",
        "@com_github_stretchr_testify//require",
    ],
)
