load("@rules_go//go:def.bzl", "go_test")

go_test(
    name = "sha256sum_test",
    srcs = [
        "helpers_test.go",
        "sha256sum_fuzz_test.go",
        "sha256sum_pentest_linux_test.go",
        "sha256sum_pentest_test.go",
        "sha256sum_pentest_unix_test.go",
    ],
    deps = [
        "//builtins/testutil",
        "//interp",
        "@com_github_stretchr_testify//assert",
        "@com_github_stretchr_testify//require",
    ],
)
