load("@bazel_skylib//lib:subpackages.bzl", "subpackages")
load("@rules_go//go:def.bzl", "go_library", "go_test")

go_library(
    name = "flagparser",
    srcs = [
        "flagparser.go",
        "noargbool.go",
    ],
    importpath = "github.com/DataDog/rshell/builtins/internal/flagparser",
    visibility = ["//builtins:__subpackages__"],
    deps = ["@com_github_spf13_pflag//:pflag"],
)

go_test(
    name = "flagparser_test",
    size = "small",
    srcs = ["flagparser_test.go"],
    embed = [":flagparser"],
    deps = ["@com_github_spf13_pflag//:pflag"],
)

filegroup(
    name = "srcs",
    srcs = glob(["**"]) + [
        "%s:srcs" % d
        for d in subpackages.all(
            allow_empty = True,
            fully_qualified = True,
        )
    ],
    visibility = ["//visibility:public"],
)
